import fs from 'fs';
let content = fs.readFileSync('src/App.tsx', 'utf8');

// 1. Add states
const regexVars = /const \[showDlpModal, setShowDlpModal\] = useState<boolean>\(false\);/;
const replacementVars = "const [showDlpModal, setShowDlpModal] = useState<boolean>(false);\n  const [duplicatePatient, setDuplicatePatient] = useState<any | null>(null);\n  const [ingestedRawText, setIngestedRawText] = useState<string>('');";
content = content.replace(regexVars, replacementVars);

// 2. Add handleSaveParsedProfile
const regexAction = /\/\/ ==========================================\n\s*\/\/ ONBOARD FORM ACTION: PDF\/Clinical Report Upload Parser/;
const replacementAction = "  const handleSaveParsedProfile = async () => {\n    if (!parsedOriginal) return;\n    try {\n      showToast('Saving evaluated profile to registry...', 'info');\n      const res = await fetch('/api/patients/save-parsed-profile', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ \n          parsedProfile: parsedOriginal,\n          rawText: ingestedRawText,\n          isUpdating: !!duplicatePatient || false\n        })\n      });\n\n      if (!res.ok) {\n        const d = await res.json();\n        throw new Error(d.error || 'Failed to save profile');\n      }\n      \n      showToast('Patient successfully added/updated in registry.', 'success');\n      setShowDlpModal(false);\n      setDuplicatePatient(null);\n      \n      await loadRecords();\n      setSelectedPatientId(parsedOriginal.patient_id);\n    } catch(err: any) {\n      showToast(err.message, 'error');\n    }\n  };\n\n  // ==========================================\n  // ONBOARD FORM ACTION: PDF/Clinical Report Upload Parser";
content = content.replace(regexAction, replacementAction);

// 3. Update handleParseClinicalNote
const regexHandleStr = "      setParsedOriginal(data.originalProfile);\n      setParsedAnonymized(data.anonymizedProfile);\n      setShowDlpModal(true);\n      showToast('DLP scan completed! Side-by-side PII scrubbed.', 'success');\n      \n      // Clear file states\n      setNoteFileBase64('');\n      setNoteFileMimeType('');\n      setNoteFileName('');\n      setMergePatientId('');\n\n      // Reload the global patients list so the new patient is immediately listed\n      await loadRecords();\n      \n      // Select the newly parsed patient automatically\n      if (data.originalProfile && data.originalProfile.patient_id) {\n        setSelectedPatientId(data.originalProfile.patient_id);\n      }";

const replacedHandleStr = "      setParsedOriginal(data.originalProfile);\n      setParsedAnonymized(data.anonymizedProfile);\n      setDuplicatePatient(data.duplicatePatient || null);\n      setIngestedRawText(data.extractedText || '');\n      setShowDlpModal(true);\n      showToast('DLP scan completed! Please review parsed data against duplications.', 'success');\n      \n      // Clear file states\n      setNoteFileBase64('');\n      setNoteFileMimeType('');\n      setNoteFileName('');\n      setMergePatientId('');";
content = content.replace(regexHandleStr.replace(/'/g, '"'), replacedHandleStr.replace(/'/g, '"'));

// 4. Update Modal UI exactly line by line
const regexModalHeader = "<div className=\"p-5 border-b border-slate-200 flex items-center justify-between bg-slate-900 text-white\">\n                <div className=\"flex items-center gap-2.5\">";
const replacedModalHeader = "{duplicatePatient && (\n                <div className=\"bg-amber-100/50 border-b border-amber-300 text-amber-900 px-5 py-3 text-sm font-medium tracking-tight flex items-start gap-4\">\n                  <span className=\"text-xl mt-0.5\">⚠️</span>\n                  <div>\n                    <h4 className=\"font-bold text-amber-800\">Duplication Warning: Matching Patient Exists</h4>\n                    <p className=\"text-amber-700/90 text-xs mt-1 leading-relaxed\">\n                      A patient matching this demographic/clinical fingerprint already exists (<strong className=\"font-mono bg-amber-200/50 px-1.5 py-0.5 rounded\">{duplicatePatient.patient_id}</strong> - {duplicatePatient.name}). \n                      Confirming below will <u>update and merge</u> this record.\n                    </p>\n                  </div>\n                </div>\n              )}\n              <div className=\"p-5 border-b border-slate-200 flex items-center justify-between bg-slate-900 text-white\">\n                <div className=\"flex items-center gap-2.5\">";
content = content.replace(regexModalHeader, replacedModalHeader);

const regexModalButton = "<button\n                  type=\"button\"\n                  onClick={() => setShowDlpModal(false)}\n                  className=\"p-1.5 px-3 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs rounded-lg cursor-pointer transition border border-slate-700 font-bold\"\n                >\n                  Onload & Dismiss\n                </button>";
const replacedModalButton = "<div className=\"flex items-center gap-3\">\n                  <button type=\"button\" onClick={() => setShowDlpModal(false)} className=\"px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs rounded-lg cursor-pointer transition border border-slate-600 font-bold\">\n                    Cancel\n                  </button>\n                  {duplicatePatient ? (\n                    <button type=\"button\" onClick={handleSaveParsedProfile} className=\"px-4 py-2 bg-amber-500 hover:bg-amber-600 border border-amber-600 text-white text-xs rounded-lg cursor-pointer transition shadow-sm font-bold flex items-center gap-2\">\n                      <span>Merge into Existing Record</span>\n                    </button>\n                  ) : (\n                    <button type=\"button\" onClick={handleSaveParsedProfile} className=\"px-4 py-2 bg-blue-600 hover:bg-blue-700 border border-blue-700 text-white text-xs rounded-lg cursor-pointer transition shadow-sm font-bold flex items-center gap-2\">\n                      <span>Confirm & Enroll Profile</span>\n                    </button>\n                  )}\n                </div>";
content = content.replace(regexModalButton, replacedModalButton);

fs.writeFileSync('src/App.tsx', content);
